import { StyleSheet } from 'react-native';
import { fontFamilies, themeColors } from '@/theme/tokens';

export const mapLocationPickerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: themeColors.white,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: themeColors.white,
    borderBottomWidth: 1,
    borderBottomColor: themeColors.gray200,
  },
  headerSpacer: {
    width: 24,
  },
  closeButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: -10,
    marginLeft: -10,
  },
  searchPanel: {
    zIndex: 2,
    padding: 12,
    backgroundColor: themeColors.white,
    borderBottomWidth: 1,
    borderBottomColor: themeColors.gray200,
  },
  routeInput: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: themeColors.gray200,
    borderRadius: 14,
    backgroundColor: themeColors.white,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  disabledRouteInput: {
    opacity: 0.45,
  },
  routeInputTextWrap: {
    flex: 1,
    minWidth: 0,
    marginLeft: 10,
  },
  routeTextInput: {
    minWidth: 0,
    paddingVertical: 4,
    fontFamily: fontFamilies.regular,
    color: themeColors.gray900,
  },
  clearInputButton: {
    marginLeft: 8,
  },
  savedLocationsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 2,
  },
  savedLocationButton: {
    maxWidth: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: themeColors.gray200,
    borderRadius: 999,
    backgroundColor: themeColors.white,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  mapContainer: {
    flex: 1,
  },
  map: {
    flex: 1,
  },
  pointerWrapper: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: -21,
    marginTop: -42,
  },
  pointerShadow: {
    shadowColor: '#000000',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 6,
  },
  currentLocationButton: {
    position: 'absolute',
    right: 16,
    bottom: 18,
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: themeColors.white,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: themeColors.gray200,
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 5,
  },
  detailPanel: {
    backgroundColor: themeColors.white,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 20,
    borderTopWidth: 1,
    borderTopColor: themeColors.gray200,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  routeSummaryPanel: {
    maxHeight: '52%',
    paddingBottom: 0,
  },
  routeSummaryContent: {
    flexGrow: 0,
  },
  routeSummaryContentContainer: {
    paddingBottom: 12,
  },
  routeSummaryStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  routeSummaryRows: {
    gap: 12,
  },
  routeSummaryRow: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: themeColors.gray200,
    backgroundColor: themeColors.gray100,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  routeActionFooter: {
    paddingTop: 12,
    paddingBottom: 20,
    borderTopWidth: 1,
    borderTopColor: themeColors.gray200,
  },
});
